
-- 1. Tabela de Capítulos
create table public.chapters (
  id bigint generated by default as identity primary key,
  name text not null,
  acronym text not null, -- Ex: RAS, CS
  description text,
  color_theme text, -- Ex: "from-blue-500 to-indigo-600"
  icon_name text, -- Nome do ícone Lucide
  cover_image_url text,
  calendar_url text, -- Link para o arquivo .ics público
  email text, -- E-mail de contato do capítulo
  keywords text[], -- NOVO: Keywords/Hashtags para vTools
  content_url text, -- NOVO: JSON string para galeria de links [{'title': '', 'url': '', 'emoji': ''}]
  members_count int default 0,
  projects_count int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Tabela de Usuários (Profiles) - ATUALIZADA COM CHAPTER_ROLES
create table public.profiles (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  role text, -- Cargo Principal / Título de Exibição (ex: Presidente do Ramo)
  avatar_initials text,
  chapter_ids bigint[], -- Array de IDs
  chapter_roles jsonb default '{}'::jsonb, -- NOVO: Mapeamento { "chapter_id": "Cargo" }
  matricula text,
  birth_date date,
  skills text[], -- Array de strings para habilidades
  photo_url text,
  bio text, -- Texto longo em Markdown para o currículo
  membership_number text, -- Novo campo
  cover_config text, -- Novo campo: URL ou Gradiente (ex: "from-blue-500...")
  social_links jsonb default '{}'::jsonb, -- Novo campo: { linkedin: '', github: '', instagram: '' }
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Tabela de Projetos - ATUALIZADA COM OWNER_IDS E TEAM_IDS
create table public.projects (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  status text, -- 'Em Andamento', 'Planejamento'
  progress int default 0,
  start_date date,
  end_date date,
  is_partnership boolean default false,
  owner_ids bigint[], -- NOVO: Array de IDs dos Gerentes (Relacional)
  team_ids bigint[], -- NOVO: Array de IDs da Equipe (Relacional)
  tags text[], -- Array de strings para tags
  chapter_ids bigint[], -- Array de IDs dos capítulos participantes (pode ser mais de um)
  checkpoints jsonb default '[]'::jsonb, -- Array de {title: string, date: string}
  notes text, -- Anotações gerais do projeto (textarea)
  content_url text, -- JSON string para galeria de links [{'title': '', 'url': '', 'emoji': ''}]
  color_theme text, -- NOVO: Gradiente visual (ex: "from-blue-600 to-purple-600")
  cover_image text, -- NOVO: URL da imagem de capa do projeto
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. Tabela de Tarefas
create table public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  status text check (status in ('todo', 'doing', 'review', 'done', 'archived')),
  priority text, -- 'alta', 'media', 'baixa', 'urgente'
  start_date date default CURRENT_DATE, -- Nova coluna
  deadline date,
  tags text[],
  attachments_count int default 0,
  content_url text, -- URL para iframe (Figma, Docs, etc)
  project_id bigint references public.projects(id) on delete cascade,
  assignee_ids bigint[], -- Array de IDs dos usuários responsáveis
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 5. Tabela de Eventos (NOVA)
create table public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  start_date timestamp with time zone not null,
  end_date timestamp with time zone not null,
  location text,
  description text,
  category text, -- NOVO: Categoria vTools
  sub_category text, -- NOVO: Subcategoria vTools
  event_type text default 'InPerson', -- NOVO: 'Virtual' ou 'InPerson'
  host_ous text[], -- NOVO: Array de strings para Organizational Units
  is_public boolean default false, -- NOVO: Define se aparece na agenda geral (Ramo) ou apenas interna
  vtools_reported boolean default false, -- NOVO: Status do reporte vTools
  meeting_minutes_url text, -- NOVO: Link da Ata
  attendees_ieee int default 0, -- NOVO: Contagem IEEE
  attendees_guests int default 0, -- NOVO: Contagem Convidados
  attendee_list jsonb default '[]'::jsonb, -- NOVO: Lista de Presença [{id, name, type}]
  chapter_id bigint references public.chapters(id),
  project_id bigint references public.projects(id),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 6. Tabela de Classificados (NOVA - Para Propostas e Ideias)
create table public.classifieds (
  id bigint generated by default as identity primary key,
  type text not null, -- 'help' (Ajuda) ou 'idea' (Ideia)
  title text not null,
  description text not null,
  image_url text,
  task_id bigint references public.tasks(id), -- Opcional: Se for pedido de ajuda vinculado a tarefa
  responsible_name text, -- Opcional
  chapter_ids bigint[], -- Opcional
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 7. Tabela de Metas do Capítulo (NOVA com period)
create table public.chapter_goals (
  id bigint generated by default as identity primary key,
  chapter_id bigint references public.chapters(id) on delete cascade,
  title text not null, -- Ex: "Crescimento 2026.1"
  description text, -- Tooltip: "Aumentar membresia em 20%"
  indicator_label text not null, -- Ex: "Novos Membros"
  current_value int default 0,
  target_value int not null,
  color text default 'bg-blue-600', -- Para customização visual
  period text default 'Anual', -- 'Mensal', 'Trimestral', 'Semestral', 'Anual'
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 8. Tabela de Ferramentas/Configurações (Multipropósito)
create table public.tools (
  id text primary key, -- ID Alfanumérico (ex: 'motivational_quotes', 'app_config')
  content text, -- JSON String para armazenar arrays, objetos, etc.
  status text default 'active', -- 'active', 'inactive'
  created_at timestamp with time zone default timezone('utc'::text, now())
);
